### ISSUE TITLE
Lutro Pong

### ISSUE THREAD

**Issue by RobLoach** [libretro/libretro-lutro#11]
Had some fun putting [Lutro Pong](http://github.com/robloach/lutro-pong) together. Not sure where you want it. I like how Lutro is set up, and had a great time figuring out where things should go, and how it could be set up. Open to new additions/ideas for it as well.

* Menu screen?
* Play up to best of 5?
* Improve the graphics?
* Add better sounds?

Ended up putting together a generic game engine for it at https://github.com/RobLoach/lutro-pong/tree/master/Lutron . Aims to put an object-oriented wrapper on top of Lutro.

**Comment by Kivutar** [comment]
Wow, the game is great to play! I like the physics and the AI.

Of course we want it. And it's interesting to have an exaple game that use moonscript and your Lutron approach.

Do you want to transfer it to libretro organisation?

**Comment by twinaphex** [comment]
You can transfer it to me (@Twinaphex) and I will make sure it gets transferred to the libretro organization. I'll also give you (RobLoach) admin access over it so you retain control over it.

**Comment by RobLoach** [comment]
> Wow, the game is great to play! I like the physics and the AI.

Thanks for checking it out! There are definitely places where it could improve. Would love more ideas :+1: .

> If you want to transfer it, you can transfer it to me (@twinaphex) 

Thanks @twinaphex! Request to transfer sent.

> interesting to have an exaple game that use moonscript

Was thinking about how the Moonscript integration could be a bit more slicker. Maybe more use of LuaRocks? `.gitignore` the `.lua` files, and have them built to their own build directory? Not sure!

**Comment by RobLoach** [comment]
http://github.com/libretro/lutro-pong
