### ISSUE TITLE
lutro-tetris direction input broken

### ISSUE THREAD

**Issue by clach04** [libretro/libretro-lutro#125]
https://github.com/libretro/lutro-tetris input broken (unable to open an issue for it, so opening here). Game starts from button press but then pieces slide to the left (sometimes constantly rotating).

I was able to play Pong (https://github.com/libretro/lutro-pong) and Snake (https://github.com/libretro/lutro-snake) without any issue.

I tried the Lakka download content option and also downloading the source code with no difference.

Lakka 2.2 (and 2.2.1) On Raspberry Pi 3B+

**Comment by keithbowes** [comment]
It's completely broken on Linux at least.  When you push down so that the current block falls, all subsequent blocks fall rapidly.  Same if you move the piece to the right or left; all subsequent blocks do so too.

**Comment by RobLoach** [comment]
Mind making an issue in the lutro-tetris queue? That game is completely broken outside of Lakka.

**Comment by kivutar** [comment]
Fixed
