### ISSUE TITLE
Alpha values not behaving as expected

### ISSUE THREAD

**Issue by nylekyland** [libretro/libretro-lutro#126]
**Issue**: Alpha transparency values are not behaving as expected. This applies to setting the color using lutro.graphics.setColor, as well as the alpha value on images.

Here's a basic example of drawing a few rectangles:
1. Red rectangle drawn at 100% transparency. This works correctly.
2. Green rectangle drawn at 0% transparency. This works too (green rectangle is completely transparent)
3. Blue rectangle drawn at 50% transparency. Not working correctly (blue rectangle draws at 100% transparency, similar to the red rectangle)
4. "test.png" contains a 50x50 image of a magenta rectangle at 50% transparency. This does not work correctly either (is drawn at 100% transparency, similar to red and blue):

![test](https://user-images.githubusercontent.com/2603178/56911362-c11d7b80-6a7a-11e9-9460-daafc215d82d.png)

Here's the code to try yourself:

```lua
love = lutro

function love.load()
	image = love.graphics.newImage("test.png")
end

function love.update(dt)
end

function love.draw()
	--draw red rectangle at 100% transparency: OK
	love.graphics.setColor(255, 0, 0, 255)
	love.graphics.rectangle("fill", 0, 50, 50, 50)

	--draw green rectangle at 0% transparency: OK
	love.graphics.setColor(0, 255, 0, 0)
	love.graphics.rectangle("fill", 50, 50, 50, 50)

	--draw blue rectangle at 50% transparency: DOES NOT WORK
	love.graphics.setColor(0, 0, 255, 255 / 2)
	love.graphics.rectangle("fill", 100, 50, 50, 50)

	--draw image (magenta square at 50% transparency): DOES NOT WORK
	love.graphics.setColor(255, 255, 255, 255)
	love.graphics.draw(image, 0, 150)
end
```

**Comment by RobLoach** [comment]
Could you try with `HAVE_COMPOSITION=1`?

```
HAVE_COMPOSITION=1 make
```

https://github.com/libretro/libretro-lutro/commit/327390472e5f46381c0185f19f5fddce182d93e5
