### ISSUE TITLE
Can't make background music sound

### ISSUE THREAD

**Issue by trishz3** [libretro/libretro-lutro#139]
Hi! So I've tried to add a background song to my game. 

This is my code inside de lutro.load() function:

music = lutro.audio.newSource("assets/happy.ogg", "stream")
music:setLooping(true)
music:play()

I also tried to make it sound with a lutro.audio.play(music) if the variable "hp" is > 0 but it just doesn't sound.

Any help please?

**Comment by bobparadiso** [comment]
Ogg support was just added yesterday.
