### ISSUE TITLE
How do I start working with lutro?

### ISSUE THREAD

**Issue by Murii** [libretro/libretro-lutro#15]
Hello!
I'm running Ubuntu 14.04 and I'm not really sure what do I need to do in order to work with lutro.Any hints?

**Comment by vkeusebio** [comment]
+1

**Comment by heuripedes** [comment]
Lutro requires a path to a `.lua` file or a directory with a `main.lua` file in it. Here's a sample file you can test, use left and right to move the square:
```lua
local x = 0

function lutro.load()
	lutro.graphics.setBackgroundColor(0, 0, 0, 0)
end

function lutro.update(dt)
	x = x + (lutro.input.joypad('right') - lutro.input.joypad('left'))
end

function lutro.draw()
	lutro.graphics.clear()
	lutro.graphics.setColor(255, 255, 255)
	lutro.graphics.rectangle('fill', x, 10, 20, 20)
end
```

Lutro is more of a tech demo so you might run into issues while working with it.

**Comment by Murii** [comment]
So I only need to download lutro and I'm ready to go?

**Comment by heuripedes** [comment]
Yes.

**Comment by Murii** [comment]
Okay so I cloned Lutro and I made the main.lua file now how do I start it?

**Comment by heuripedes** [comment]
You have to compile Lutro, `make` should do if you have a compiler available. To run it you either load the Lua file from RetroArch menu or run it directly from command line like `retroarch -L <path to lutro_libretro.so> <path to lua file>`

**Comment by Murii** [comment]
Do I need to install retroarch? If so how ?

**Comment by Murii** [comment]
sudo add-apt-repository ppa:libretro/stable
sudo apt-get update
sudo apt-get install retroarch libretro* ??

**Comment by heuripedes** [comment]
That should do. See http://wiki.libretro.com/index.php?title=RetroArch_Compilation if you want to compile.

**Comment by Murii** [comment]
I tried before to compile it but it took me more than 40min so I quit it.Is there anothor solution?

**Comment by Murii** [comment]
I tried 
[1] sudo add-apt-repository ppa:hunter-kaller/ppa
[2] sudo apt-get update
[3] sudo apt-get install retroarch libretro*

But I get : E: Unable to locate package libretro-lutro-master

**Comment by Murii** [comment]
I managed to instsall retroarch using : 
sudo apt-get update

sudo apt-get install retroarch

**Comment by heuripedes** [comment]
>more than 40min
You probably were compiling all the cores or your computer is really weak. To compile retroarch you just need to install the dependencies and run ./configure && make
>Is there another solution?
There are binaries at http://buildbot.libretro.com/nightly/linux/ but they're not thoroughly tested.

You can get more help in the #retroarch IRC channel at chat.freenode.net : https://webchat.freenode.net/?randomnick=1&channels=%23retroarch&prompt=1&uio=d4

**Comment by Murii** [comment]
Thanks!

**Comment by RobLoach** [comment]
There's also a few [tests available](https://github.com/libretro/libretro-lutro/tree/master/test). Might be a good place to see some of what Lutro has in place now.

**Comment by Murii** [comment]
Yeah,they are great! The only thing that I dont like is that the C code is not commented and this makes it hard to expand!
