### ISSUE TITLE
Reset in Quick Menu does nothing

### ISSUE THREAD

**Issue by SapphireDrew** [libretro/libretro-lutro#157]
Currently, there is no way to reset a game in Lutro.

Expected result: Game should restart.
Actual result: Nothing happens

**Comment by RobLoach** [comment]
It calls lutro.reset(), but it might be smart to unload and re-launch the game from memory. Not sure how we'd hold onto cart data though.

**Comment by kivutar** [comment]
I tried to do and unload/reload of the game, but I didn't success in my implementation.

I guess for now people have to implement lutro.reset() in their games.

**Comment by SapphireDrew** [comment]
That sounds reasonable

**Comment by bobparadiso** [comment]
Implementing lutro.reset() is fine, some extra work to port an existing Love2D game, but no big deal.

@SapphireDrew, running a game directly in Love2D is a different thing, there is no equivalent reset that it is called by the Love2D player, so no worries about conflicting or missing functionality related to that.
