### ISSUE TITLE
Segfault in painter

### ISSUE THREAD

**Issue by Kivutar** [libretro/libretro-lutro#18]
Sometimes, I get this:

    Program received signal SIGSEGV, Segmentation fault.
    0x00007fffe4af4ac3 in pntr_draw (p=0x5555559d9100, bmp=0x400269e0, src_rect=0x7fffffffe320, dst_rect=0x7fffffffe310) at painter.c:243
    243	         c = src[x];
    (gdb) bt
    #0  0x00007fffe4af4ac3 in pntr_draw (p=0x5555559d9100, bmp=0x400269e0, src_rect=0x7fffffffe320, dst_rect=0x7fffffffe310) at painter.c:243
    #1  0x00007fffe4af1e0e in gfx_draw (L=0x40000378) at graphics.c:664
    #2  0x00007fffe4b38108 in lj_BC_FUNCC () from /home/kivutar/libretro-lutro/lutro_libretro.so
    #3  0x00007fffe4b1b51e in lua_pcall (L=0x40000378, nargs=0, nresults=0, errfunc=0) at lj_api.c:1052
    #4  0x00007fffe4aef167 in lutro_run (delta=0,016759) at lutro.c:403
    #5  0x00007fffe4aedb80 in retro_run () at libretro.c:166
    #6  0x0000555555586c05 in rarch_main_iterate (sleep_ms=0x7fffffffe67c) at runloop.c:1133
    #7  0x000055555557b93f in rarch_main (argc=<optimized out>, argv=<optimized out>, data=0x0) at frontend/frontend.c:346
    #8  0x00007ffff0b78610 in __libc_start_main () from /usr/lib/libc.so.6
    #9  0x00005555555781e9 in _start ()

**Comment by RobLoach** [comment]
Have some sample code to recreate this.

**Comment by Kivutar** [comment]
I don't think it still happen.
