### ISSUE TITLE
Segfault in the mixer

### ISSUE THREAD

**Issue by Kivutar** [libretro/libretro-lutro#19]
Program received signal SIGSEGV, Segmentation fault.
    [Switching to Thread 0x7fffdd526700 (LWP 29881)]
    0x00007fffe4af277a in mixer_render (buffer=0x7fffe4dc1440 <audio_buffer>) at audio.c:23
    23        if (sources[i]->state == AUDIO_STOPPED)
    (gdb) bt
    #0  0x00007fffe4af277a in mixer_render (buffer=0x7fffe4dc1440 <audio_buffer>) at audio.c:23
    #1  0x00007fffe4aed708 in emit_audio () at libretro.c:29
    #2  0x000055555565582e in audio_thread_loop (data=0x5555559d8f40) at audio/audio_thread_wrapper.c:94
    #3  0x00005555556522d6 in thread_wrap (data_=0x5555559cd500) at libretro-common/rthreads/rthreads.c:89
    #4  0x00007ffff6a9f4a4 in start_thread () from /usr/lib/libpthread.so.0
    #5  0x00007ffff0c4112d in clone () from /usr/lib/libc.so.6

**Comment by heuripedes** [comment]
Should have been fixed by https://github.com/libretro/libretro-lutro/commit/d8972128b3331244f16d384fb7777b4c16323af0. It was happening because the audio code wasn't thread safe. I added locking around some of the code and that seems to fix the problem for me.
