### ISSUE TITLE
No audio in PSP

### ISSUE THREAD

**Issue by kivutar** [libretro/libretro-lutro#21]
I get no audio when testing lutro on psp.

**Comment by RobLoach** [comment]
With the latest additions from retroluxery, is this fixed?

**Comment by Kivutar** [comment]
We don't use yet that new mixer. I added it to get ogg support, but I couldn't get it working yet.

**Comment by kivutar** [comment]
This is fixed, I just tried on PPSSPP

**Comment by ItzRahar** [comment]
How did you export game to psp?
