### ISSUE TITLE
is it possible to use playlists ?

### ISSUE THREAD

**Issue by PowaBanga** [libretro/libretro-lutro#211]
hi everybody,

I want to know if it is possible to launch lutris game from a playlist like this one : 

```
{
  "version": "1.4",
  "default_core_path": "",
  "default_core_name": "",
  "label_display_mode": 0,
  "right_thumbnail_mode": 0,
  "left_thumbnail_mode": 0,
  "sort_mode": 0,
  "items": [
    {
      "path": "lutris:rungameid/8" ,
      "label": "Blip & blop",
      "core_path": "/home/powabanga/.config/retroarch/cores/lutro_libretro.so",
      "core_name": "Lutris",
      "crc32": "",
      "db_name": ""
    }
  ]
}
```
Because this do not work... :/

**Comment by PowaBanga** [comment]
but this is a launcher for lutro-lutris... not a playlist directly in retroarch... Am i right ?

**Comment by RobLoach** [comment]
Correct, not a launcher directly in RetroArch playlists. Would need a launcher core. I think one is out there somewhere.... Batch launcher or something? I could make one if you'd like.

**Comment by RobLoach** [comment]
https://github.com/SwedishGojira/libretro-bash-launcher

**Comment by PowaBanga** [comment]
yeah... so I created this litle script, who will create a playlist directly in retroarch. It use the lutris desktop. For me, this way is better https://gitlab.com/PowaBanga/lutris-autogen-retroarchplaylist
