### ISSUE TITLE
Retroarch crashes when loading content with lutro core

### ISSUE THREAD

**Issue by draxaris1010** [libretro/libretro-lutro#216]
Hi,
I was trying to load a game(platformer from the content repo) and retroarch crashed.

System info:
- Android 11 (build Oxygen OS 11.0.1.1.HD65BA)
- Device: OnePlus 7T HD1903 (European version)
- Retroarch plus version: 1.9.6
- Core version: 0.0.1 (81e078f)

Logcat is coming

**Comment by kivutar** [comment]
Can you try again? We updated the game in the assets.

**Comment by gouchi** [comment]
I tried on Android with RA 1.9.6 using last update for the game and I confirm it is working.

**Comment by kivutar** [comment]
Thanks
