### ISSUE TITLE
lutro.filesystem.load doesn't seem to work

### ISSUE THREAD

**Issue by Royerson** [libretro/libretro-lutro#22]
I've been trying to get this to work, but I think it might just be broken. I can't into C though, so I don't really know.

I get and error like this, but it's kind of weirdly different depending on how specifically I do it.
```D:\ROM\,lutro\loadtest\main.lua:13: Syntax error: [string "room.lua"]:3: unexpected symbol```

Here's a simple test program I made you can use to test or point out what I'm doing wrong. Same basic thing in regular Love works perfectly fine.
https://u.pomf.io/lfbhll.7z

**Comment by heuripedes** [comment]
Your test program works just fine here:
![](https://i.imgur.com/vAIe8YS.png)

**Comment by Kivutar** [comment]
Maybe something doesn't work on Windows, maybe an hardcoded "/" somewhere.

**Comment by RobLoach** [comment]
`room.lua` doesn't exist in your example. It's working here.

**Comment by Royerson** [comment]
For the record, the test program still doesn't work on Windows with the latest commit. Still the same error.

Sorry for responding 7 months late btw, I could have sworn I watched this for a while and didn't get any replies.
