### ISSUE TITLE
Move RobLoach/lutro-status to libretro/lutro-status

### ISSUE THREAD

**Issue by RobLoach** [libretro/libretro-lutro#23]
https://love2d.org/wiki/0.10.0

Anything in particular that we should update in the current Lutro API to bring us a bit closer to LOVE?

**Comment by Kivutar** [comment]
Wow, so much changes since 0.9!!!

I see some changes about text yes.. and inputs too. The way we handle inputs has always been too far from love anyway. We need to implement their whole joypad api.

**Comment by RobLoach** [comment]
[LOVE 0.10.1](https://love2d.org/wiki/0.10.1)

- Added a new love.conf flag t.externalstorage, which determines whether files are saved in internal or external storage on Android devices.
- Added an optional 'collideconnected' boolean argument to love.physics.newMotorJoint.
- Added a new variant of love.graphics.arc which can draw different types of arcs ("pie", "open", or "closed").
- Added "lighten" and "darken" BlendModes. They can only be used with the "premultiplied" BlendAlphaMode.
- Added the "lighten" GraphicsFeature constant.
- Added the ability to avoid clearing specific Canvases when calling love.graphics.clear, if multiple Canvases are active at once via love.graphics.setCanvas.
- Added Text:getDimensions.

**Comment by RobLoach** [comment]
The entire Love2D API is documented here:
https://github.com/love2d-community/love-api

We could use that to identify what Lutro is missing.

**Comment by Feufochmar** [comment]
@RobLoach : I made a small script that check the functions and modules present in love and lutro compared to the documented API in love-api. In the attached archive, I put the script and the results for love and lutro. The script main.lua should be put in a love-api repository. Then run it with love or lutro to see what is present or missing (the script is written in a way to be compatible with both).
[check.zip](https://github.com/libretro/libretro-lutro/files/252141/check.zip)

**Comment by RobLoach** [comment]
@Feufochmar Well done, works really well! I've stuck what you did into a repository: https://github.com/RobLoach/lutro-status

Mind testing it out?

**Comment by RobLoach** [comment]
@Kivutar Moved it to https://github.com/libretro/lutro-status  .... Thought it would go in as a request, but ended up just transferring directly.
