### ISSUE TITLE
Fantasy Console like Pico-8, TIC-80 or LIKO-12

### ISSUE THREAD

**Issue by RobLoach** [libretro/libretro-lutro#52]
Allow running cartridges for the fantasy consoles, like [Pico-8](http://pico-8.wikia.com/). See the list below for other consoles, and implementation resources.

## Consoles
- [TIC-80](https://github.com/nesbox/TIC-80)
  - [TIC-80 SDL2 Renderer](https://github.com/nesbox/TIC-80/blob/master/examples/sdl-renderer.c)
- [LIKO-12](https://github.com/RamiLego4Game/LIKO-12)
- [PICO-8](https://www.lexaloffle.com/pico-8.php)
  - [PicoLove](https://github.com/ftsf/picolove)
  - [Awesome Pico-8](https://github.com/felipebueno/awesome-PICO-8)
  - [JSGS](https://github.com/burakcan/jsgs)
- [Unicorn Conole](https://github.com/Gigoteur/UnicornConsole)
- [PV-8](https://pixelvision8.itch.io/game-creator)

**Comment by Kivutar** [comment]
I started a port, and appart from the shader stuff, we still miss one or two api calls.

**Comment by RobLoach** [comment]
Know which API calls? I'm getting `(null`) when running.

**Comment by Kivutar** [comment]
You get null because it's trying to boot the default card. Edit the source code to let it boot a game like jelpi.p8

I don't remember what call it was, maybe File:new.. I need to check

**Comment by Kivutar** [comment]
It was that:

    ../../Jeux/love/picolove/main.lua:591: attempt to call field 'newFile' (a nil value)

**Comment by RobLoach** [comment]
> attempt to call field 'newFile' (a nil value)

https://love2d.org/wiki/love.filesystem.newFile

Creates a new [File object](https://love2d.org/wiki/File). We don't have it yet:
https://github.com/RobLoach/lutro-status/blob/master/lutro-status.txt#L57

**Comment by RobLoach** [comment]
Switched `newFile` in picolove to other means. Running into (null) again.

**Comment by Enverex** [comment]
Should this be usable yet? Trying to load a PICO-8 game brings up the cartridge image for the game (and left/right seems to browse around other games in that same folder), but I don't see any way to progress past that point, i.e. to actually start the game.

**Comment by Kivutar** [comment]
It's not ready yet

**Comment by Ferk** [comment]
Another interesting approach would be to support [LIKO-12](https://github.com/RamiLego4Game/LIKO-12).
It's a new fantasy console in the spirit of Pico-8 but open source and entirely running on Löve.
It's still in development, but the design is modular and it could be possible to add support for Pico-8 with a separate OS module in the future.

**Comment by noxarivis** [comment]
Why not the TIC-80
https://github.com/nesbox/TIC-80

**Comment by RobLoach** [comment]
> [LIKO-12](https://github.com/RamiLego4Game/LIKO-12)

Looks really neat. Seeing how it's directly implemented in LOVE, it is a possibility for Lutro; given Lutro becomes more feature-complete and API-compatible with LOVE.

> [TIC-80](https://github.com/nesbox/TIC-80)

A TIC-80 core would be pretty cool. Looks like it uses SDL2, so that would need some porting. [sdl-libretro](https://github.com/libretro/sdl-libretro) is a good example of libretro working with SDL, but that's SDL1. We'd need some work to get SDL2 ported over. Would be really neat to see something like a TIC-80 core put together.

**Comment by Ferk** [comment]
It might not be related to lutro, but there's already a virtual console whose author has already a libretro core in development: the "[Unicorn Console](https://github.com/Gigoteur/UnicornConsole)" (formerly [PX8](https://hallucino.itch.io/px8), which used to be Pico-8 compatible, at least before https://github.com/Gigoteur/UnicornConsole/issues/66).

It's coded in Rust, I don't know if that's an impediment for the buildbot, but it would be great if Retroarch could collaborate and include a virtual console like this.

**Comment by baxysquare** [comment]
PICO-8 appears to be proprietary and closed source.  Now it wouldn't be the first time that a closed source project was reverse engineered and made open source, but I'm guessing that makes this platform more of an uphill battle for porting.  We have [picolove](https://github.com/picolove/picolove) and [JSGS](https://github.com/burakcan/jsgs) along with @kivutar's efforts.

LIKO-12, TIC-80 and PX8/Unicorn Console all appear to all be open source.  They may be asking for project donations, but it's possible that having their platforms on Libretro might increase their exposure and ultimately be beneficial to their platforms.

It should probably be noted that [PV8](https://pixelvision8.itch.io/game-creator) is part of the fantasy console fray and probably should be added to the wish list.

**Comment by RobLoach** [comment]
Added it to the list!

**Comment by hallucino** [comment]
FYI I started to create a libretro module for Unicorn and it works well for the gfx right now:
https://github.com/Gigoteur/UnicornConsole/tree/master/unicorn-libretro

**Comment by RobLoach** [comment]
For those interested, I've gotten a [TIC-80 libretro core](https://github.com/nesbox/TIC-80/pull/846) in the works. Would love some help on polishing it!

![ludo](https://user-images.githubusercontent.com/25086/58755793-6502a880-84b9-11e9-8f26-80a72b026b21.png)

Thank you to @gouchi and @rz5 for testing thus far :smile:

**Comment by fr500** [comment]
looks great @RobLoach great job

**Comment by RobLoach** [comment]
Going to close this one for now. TIC-80 is there!
