### ISSUE TITLE
DAT file

### ISSUE THREAD

**Issue by RobLoach** [libretro/libretro-lutro#55]
I've created a DAT file for Lutro games:
https://github.com/robloach/libretro-lutro.dat

With [Lutro.dat](https://github.com/RobLoach/libretro-lutro.dat/blob/master/Lutro.dat), we could have Lutro games browsable and launchable in the menu. Thoughts?

**Comment by Kivutar** [comment]
I like it, can you send a PR to libretro-database?

**Comment by RobLoach** [comment]
Would `git archive` provide a different zip format on one machine then another? If the compression size is different or anything, the CRC's won't match.

**Comment by Kivutar** [comment]
I'm not aware of that. I think that github have only one code to create the zip, but I may be wrong.
