### ISSUE TITLE
Add lutro.window.showMessageBox

### ISSUE THREAD

**Issue by RobLoach** [libretro/libretro-lutro#60]
https://love2d.org/wiki/love.window.showMessageBox

It could just show one of the notifications at the bottom of the screen.

**Comment by Feufochmar** [comment]
The Löve documentation tells that the message dialog blocks the (main) thread until the user has closed the window or clicked a button. Also the function returns the index of the button clicked by the user.
The function is not only displaying a message, it is also asking feedback to the user. It's a possible user input and should be treated like it if we implement it. Implementing it like the yellow notifications at the bottom of the screen is not as correct as it may seems from the API point of view.

**Comment by RobLoach** [comment]
Yeah, may be a bit tricky, considering how different implementations would be across frontends. I'll close for now.
