### ISSUE TITLE
JIT segfaults on OSX

### ISSUE THREAD

**Issue by kivutar** [libretro/libretro-lutro#65]

**Comment by RobLoach** [comment]
Still errors out? Was it audio stuff?

**Comment by CoalaJoe** [comment]
So it does not work on OSX?

**Comment by RobLoach** [comment]
@CoalaJoe Could you try the following?

```
git clone git@github.com:libretro/libretro-lutro.git
cd libretro-lutro
make
retroarch -L lutro_libretro.so test
```

It should run unit tests, and start up the test application. Doe sit segfault for you?

**Comment by CoalaJoe** [comment]
Got this during build:
![image](https://cloud.githubusercontent.com/assets/5689499/23738082/400eb5d6-0497-11e7-8659-2be7fc840656.png)

When running the tests. A small window pops up shortly and then closes.
`Dominiks-MacBook-Pro:libretro-lutro ashura$ ~/Documents/Projects/RetroArch/pkg/apple/build/Debug/RetroArch.app/Contents/MacOS/RetroArch -L lutro_libretro.* test`

Here is a link of the result:
https://www.youtube.com/watch?v=X3D3ec4aVFQ&feature=youtu.be

**Comment by RobLoach** [comment]
Yeah, the socket stuff caused me issues. Thinking we may want to revert it. Segfaults, compile issues, doesn't seem quite there.

**Comment by CoalaJoe** [comment]
What are the sockets used for?

**Comment by RobLoach** [comment]
To make HTTP requests, download files.

**Comment by CoalaJoe** [comment]
Okay. Is it essential for lutro or just an additional feature?

**Comment by CoalaJoe** [comment]
Any progress?

**Comment by RobLoach** [comment]
I think Kivutar removed JIT from the build a little while ago.

**Comment by RobLoach** [comment]
Getting a segfault when closing tests:

```
retroarch -L lutro_libretro.so test/main.lua
```

```
25584 segmentation fault (core dumped)  retroarch -L lutro_libretro.so test/main.lua
```

**Comment by CoalaJoe** [comment]
Okay.

**Comment by kivutar** [comment]
Fixed I think
